language: python

env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  matrix:
    - TOXENV=py27

sudo: true

cache:
  - $HOME/.pip-cache

install:
  - pip install coveralls
  - pip install tox

before_script:
  - sudo apt-get update
  - sudo apt-get install enchant

script:
  - python setup.py install
  - nosetests
  - coverage run --source=phrase_recognizer setup.py test

after_failure:

after_success:
  - coveralls

branches:
  only:
    - master
